### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by leckylao** [smearle/gym-city#8]
I am running the latest code and having the following error, looks like it's trying to connect to a server but the Visdom is up running

```
Traceback (most recent call last):
  File "train.py", line 574, in <module>
    main()
  File "train.py", line 26, in main
    trainer = Trainer()
  File "train.py", line 113, in __init__
    args=args)
  File "/usr/src/app/envs.py", line 296, in make_vec_envs
    envs = SubprocVecEnv(envs)
  File "/usr/src/app/subproc_vec_env.py", line 83, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```

Also notice multiple lines of the following messages, also seems trying to connect to server. 
```
Unable to init server: Could not connect: Connection refused
```

Also notice multiple lines of the following messages
```
MicropoligGenericEngine initGamePython: This should be called at the end of the concrete subclass's __init__ method.
```

Any idea what went wrong?

**Comment by smearle** [comment]
You need to launch the visdom server as described in the Readme. I think only the second error message is relevant here. First is generic "I was multiprocessing and something went wrong", third is a warning that came with the original micropolis as well, I believe. Or, you can just ignore these messages. The training/evaluation reward graphs will be output as png files anyway.

**Comment by leckylao** [comment]
Visdom is up and running fine on 8097. Not sure why it can't connect. And looks like it try to connect when gym.make(env), can I confirm so it require to connect to Visdom while training? How do I debug the connection?

**Comment by smearle** [comment]
Strange. Does the code work otherwise?
I think I've been getting this bug too, but simply ignoring it and referring to the "png" files for training/eval reward graphs. Keep me in the loop if you'd like to try hunting down the bug here.

**Comment by leckylao** [comment]
No, the trained_models folder is empty

**Comment by leckylao** [comment]
I am now running Ubuntu VM and can confirm this issue is docker specific. In docker Visdom server stopped with message  `INFO:root:Application Started` and missing `You can navigate to http://localhost:8097`. And when I ctrl-c from Visdom in docker it shows `You can navigate to http://dfdfaweadsss:8097`. So I guess the issue is related to Visdom trying to get hostname from docker. And I reckon adding this to README that due to this running in docker is not supported.

**Comment by smearle** [comment]
Aha, thank you for getting to the bottom of this docker issue! For now, you're good to simply comment out the import I believe. The import is because I've been toying around with applying the training loop in this repo to the environments in the repo for "PCGRL" (and on this experimental branch): https://github.com/amidos2006/gym-pcgrl/tree/FractalNet
