### ISSUE TITLE
No module named 'gym_pcgrl'

### ISSUE THREAD

**Issue by leckylao** [smearle/gym-city#9]
I am on the pcgrl_mix branch and having this no module error. And I've tried renamed gym_city to gym_pcgrl in setup.py and rerun `make install` and `pip3 install -e .` but still having this error. Any idea what else need to change?

**Comment by leckylao** [comment]
https://github.com/smearle/gym-city/issues/8#issuecomment-715425519

**Comment by smearle** [comment]
Aha, whoops, sorry for posting in the wrong thread!
